/* tslint:disable */
/* eslint-disable */
/**
 * Vybe Challenge API
 * Vybe Challenge API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface WalletBalanceDto
 */
export interface WalletBalanceDto {
    /**
     * Wallet address
     * @type {string}
     * @memberof WalletBalanceDto
     */
    wallet: string;
    /**
     * Wallet balance
     * @type {number}
     * @memberof WalletBalanceDto
     */
    balance: number;
}

/**
 * Check if a given object implements the WalletBalanceDto interface.
 */
export function instanceOfWalletBalanceDto(value: object): value is WalletBalanceDto {
    if (!('wallet' in value) || value['wallet'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    return true;
}

export function WalletBalanceDtoFromJSON(json: any): WalletBalanceDto {
    return WalletBalanceDtoFromJSONTyped(json);
}

export function WalletBalanceDtoFromJSONTyped(json: any): WalletBalanceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'wallet': json['wallet'],
        'balance': json['balance'],
    };
}

export function WalletBalanceDtoToJSON(value?: WalletBalanceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'wallet': value['wallet'],
        'balance': value['balance'],
    };
}

